name: Deploy
on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
        - name: 'Checkout'
          uses: actions/checkout@v2
        - name: 'Deploy'
          run: echo "Deploying!"
        - name: 'Login to Azure'
          uses: azure/login@v1
          with:
              creds: ${{ secrets.SERVICE_PRINCIPAL }}
